In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
# Load the CSV file
df = pd.read_csv('/kaggle/input/mall-customers/Mall_Customers.csv')
# Display the first 10 rows
df.head(10)

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40
5           6  Female   22                  17                      76
6           7  Female   35                  18                       6
7           8  Female   23                  18                      94
8           9    Male   64                  19                       3
9          10  Female   30                  19                      72

In [4]:
# Check for duplicated rows in the DataFrame
df.duplicated().sum()

0

In [5]:
# Display general information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [6]:
# Show the number of rows and columns.
df.shape

(200, 5)

In [7]:
# Group the data by 'Genre' and calculate basic statistics for the 'Age' column
df.groupby(['Genre'])['Age'].agg(['count','min','max','median','mean'])

        count  min  max  median       mean
Genre
Female    112   18   68    35.0  38.098214
Male       88   18   70    37.0  39.806818

In [8]:
# Display the 5 customers with the highest Spending Scores
display(df.loc[df['Spending Score (1-100)'].nlargest(5).index])
# Display the 5 customers with the lowest Spending Scores
display(df.loc[df['Spending Score (1-100)'].nsmallest(5).index])

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
11           12  Female   35                  19                      99
19           20  Female   35                  23                      98
145         146    Male   28                  77                      97
185         186    Male   30                  99                      97
127         128    Male   40                  71                      95

     CustomerID Genre  Age  Annual Income (k$)  Spending Score (1-100)
156         157  Male   37                  78                       1
158         159  Male   34                  78                       1
8             9  Male   64                  19                       3
30           31  Male   60                  30                       4
32           33  Male   53                  33                       4

In [9]:
# Select the customer(s) with the maximum Spending Score
# Select the customer(s) with the minimum Spending Score
score_max = df[df['Spending Score (1-100)'] == df['Spending Score (1-100)'].max()]
score_min = df[df['Spending Score (1-100)'] == df['Spending Score (1-100)'].min()]
extremes = pd.concat([score_max, score_min])# Combine both datasets
display(extremes)

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
11           12  Female   35                  19                      99
156         157    Male   37                  78                       1
158         159    Male   34                  78                       1

In [17]:
# Create a new DataFrame containing customers with high Spending Scores (≥ 71)
# Sort Spending Score in descending order
high_score = df[df['Spending Score (1-100)'] >= 71 ].sort_values(by=['Spending Score (1-100)'], ascending=[False])
display(high_score[:10])
len(high_score.index)# Count how many index values correspond to the highest scores.

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
11           12  Female   35                  19                      99
19           20  Female   35                  23                      98
145         146    Male   28                  77                      97
185         186    Male   30                  99                      97
167         168  Female   33                  86                      95
127         128    Male   40                  71                      95
7             8  Female   23                  18                      94
141         142    Male   32                  75                      93
163         164  Female   31                  81                      93
33           34    Male   18                  33                      92

54

In [11]:
# Display the count of each gender in the high Spending Score group
high_score['Genre'].value_counts()

Genre
Female    32
Male      22
Name: count, dtype: int64

In [19]:
# Group the genres with the highest scores and display basic statistics.
high_score_genre = high_score.groupby('Genre')['Spending Score (1-100)'].agg(['count','min','max','mean'])
display(high_score_genre)

        count  min  max       mean
Genre
Female     32   71   99  82.125000
Male       22   73   97  84.545455